#dynamic_title = true
live_config_reload = true
#render_timer = false
#tabspaces = 4

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x303030"
blue = "0x0000FF"
cyan = "0x00FFFF"
green = "0x00FF00"
magenta = "0xFF00FF"
red = "0xFF0000"
white = "0xFFFFFF"
yellow = "0xFFFF00"

[colors.normal]
black = "0x000000"
blue = "0x000080"
cyan = "0x008080"
green = "0x008000"
magenta = "0x800080"
red = "0x800000"
white = "0x808080"
yellow = "0x808000"

[colors.primary]
background = "0x000080"
foreground = "0xFFFFFF"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
#scale_with_dpi = true
size = 18

[font.bold]
family = "PxPlus IBM VGA 8x16"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "PxPlus IBM VGA 8x16"

[font.normal]
family = "PxPlus IBM VGA 8x16"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
#auto_scroll = true
#faux_multiplier = 1
history = 1000
multiplier = 1

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 1.0

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 6
y = 6
