name: xmonad-vem
version: 0.0.11

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base
  - containers
  - directory
  - filepath
  - process
  - regex-tdfa
  - utf8-string
  - unix
  - X11 >= 1.10
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17
  - xmobar

source-dirs:
  - src

executables:
  xmonad:
    main: xmonad.hs
    dependencies:
      - xmonad
  xmobar:
    main: xmobar.hs
    dependencies:
      - xmobar
